### ISSUE TITLE
Place a demo folder inside the repo for testing new changes

### ISSUE THREAD

**Issue by itaditya** [kodedninja/microne#3]

**Comment by kodedninja** [comment]
It's kind of funny because I've just removed it today, because it took more space than the lib itself. I'll try to come up with something more lightweight.

**Comment by itaditya** [comment]
You can put the demo folder in `.npmignore` file

**Comment by itaditya** [comment]
Gr8

**Comment by kodedninja** [comment]
Thanks for the tips @itaditya :D

**Comment by itaditya** [comment]
Happy to help @kodedninja :+1:
